# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929ea2807f79ef434ad03330314d20ec893004fe49f367d7a97874dd6ef5adb53b0fc375e07d429572f1e9b5ca7924f2ad237091fe318a203cfe0db4914cf1fb

test:
  secret_key_base: 74a71e3057b7ee1432bc2717672d2c247670b0eae94b189542406576fd1ccefbd2e1c7a8db358b81018f2202cf76e62f1982e2db49e6f5a2c75c54780f3100ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
